#' Plot trace plots for MCMC chains
#'
#' This function plots trace plots for the MCMC chains generated by WinBUGS.
#'
#' @param bugs.out The output object from `R2OpenBUGS::bugs()`.
#' @param parameter The parameter name to plot. If NULL, it will plot for all parameters.
#'
#' @return A trace plot for the MCMC chains.
#' @export

plot_trace <- function(bugs.out, parameter = NULL) {

  # Load necessary package
  library(coda)

  # Convert to MCMC object
  #mcmc.output <- read.bugs(bugs.out)
  mcmc_samples <- read.bugs(bugs.out)

  # If a specific parameter is provided, filter by that
  if (!is.null(parameter)) {
    parameter_samples <- mcmc_samples[, grep(parameter, colnames(mcmc_samples))]
    traceplot(parameter_samples)
  } else {
    # Plot trace plot for all parameters
    traceplot(mcmc_samples)
  }
}
